### ISSUE TITLE
View log in system with systemd

### ISSUE THREAD

**Issue by bobylive** [sektioneins/suhosin#113]
Maybe need to update project document, when using suhosin in CentOS 7, the option 'suhosin.log.file.name' was unavailable, because the log of suhosin will store by systemd and need to view the log by using this comment:

`journalctl | grep "suhosin"`

**Comment by bef** [comment]
Thank you for your suggestion. I'm not sure what to do here. If CentOS patched out the `suhosin.log.file.name` option, they should update the documentation accordingly.
