### ISSUE TITLE
http://download.suhosin.org is not acting properly

### ISSUE THREAD

**Issue by bjacquin** [sektioneins/suhosin#116]
Hi,

Redirections on download.suhosin.org from HTTP to HTTPS are not handled properly:

```
$ curl -D - http://download.suhosin.org/suhosin-patch-5.2.16-0.9.7.patch.gz
HTTP/1.0 301 Moved Permanently
Location: https:///suhosin-patch-5.2.16-0.9.7.patch.gz
Content-Length: 0
Date: Sun, 17 Sep 2017 23:42:01 GMT
Connection: keep-alive
```

The domain name is missing in the redirection.

I believe the URL should be rewritten to `https://download.suhosin.org/suhosin-patch-5.2.16-0.9.7.patch.gz`

Cheers,
Bertrand

**Comment by bef** [comment]
fixed.
