### ISSUE TITLE
HTTPS certificate expired on suhosin.org

### ISSUE THREAD

**Issue by williamdes** [sektioneins/suhosin#119]
https://travis-ci.org/github/phpmyadmin/phpmyadmin/jobs/661674043#L405

**Comment by bef** [comment]
thanks. resolved.

**Comment by williamdes** [comment]
Thank you !
Very nice avatar ;)

**Comment by williamdes** [comment]
We are having timeouts to your website: https://travis-ci.org/github/phpmyadmin/phpmyadmin/jobs/689814752#L453
